project:
  type: book
  output-dir: docs

book:
  title: "CEMPRA Guidance Document"
  favicon: favicon.ico
  subtitle: "Cumulative Effects Model for Prioritizing Recovery Actions (CEMPRA)"
  date: last-modified
  site-url: https://mattjbayly.github.io/CEMPRA_documentation/
  repo-url: https://github.com/mattjbayly/CEMPRA_documentation/
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_stressor_response.qmd
    - 03_pathways_endpoints.qmd
    - 04_initial_setup.qmd
    - 05_data_inputs.qmd
    - 06_r_shiny_app.qmd
    - 07_life_cycle_model.qmd
    - 08_stressor_response_library.qmd
    - 09_case_study_applications.qmd
    - 10_r_package_tutorials.qmd
    - 11_conclusions.qmd
    - references.qmd
  appendices:
    - appendix_interaction_matrix.qmd
    - appendix_socio_economic.qmd
  google-analytics:
    tracking-id: "G-3SJZ32N1H9"
    anonymize-ip: true
  cookie-consent: true
  body-footer: | 
    Leave questions and comments below (via your GitHub account)
  comments: 
    utterances:
      repo: mattjbayly/CEMPRA_documentation

bibliography: references.bib
csl: apa.csl

format:
  html:
    toc: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

